/******************************************************************************/
/*            Generated by IBExpert 2008.02.19 30/09/2005 21:54:02            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

SET CLIENTLIB 'fbclient.dll';

CREATE DATABASE 'localhost:D:\Comercial\DB\DBVendas.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET ISO8859_1;



/******************************************************************************/
/*                                  Domains                                   */
/******************************************************************************/

CREATE DOMAIN DM_LONGTEXT AS
VARCHAR(75) CHARACTER SET ISO8859_1;

CREATE DOMAIN DM_SMALLTEXT AS
VARCHAR(20) CHARACTER SET ISO8859_1;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTES_ID;
SET GENERATOR GEN_CLIENTES_ID TO 0;

CREATE GENERATOR GEN_PERFIL_ID;
SET GENERATOR GEN_PERFIL_ID TO 0;

CREATE GENERATOR GEN_PRODUTOS_ID;
SET GENERATOR GEN_PRODUTOS_ID TO 0;

CREATE GENERATOR GEN_USUARIOS_ID;
SET GENERATOR GEN_USUARIOS_ID TO 0;

CREATE GENERATOR GEN_VENDAS_ID;
SET GENERATOR GEN_VENDAS_ID TO 0;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE CLIENTES (
    CLIENTEID  INTEGER NOT NULL,
    NOME       DM_LONGTEXT COLLATE PT_BR,
    ENDERECO   DM_LONGTEXT COLLATE PT_BR,
    BAIRRO     DM_SMALLTEXT COLLATE PT_BR,
    CIDADE     DM_SMALLTEXT COLLATE PT_BR,
    CEP        CHAR(9) CHARACTER SET ISO8859_1 COLLATE PT_BR,
    UF         CHAR(2) CHARACTER SET ISO8859_1 COLLATE PT_BR,
    EMAIL      DM_LONGTEXT COLLATE PT_BR,
    TELEFONE   DM_SMALLTEXT COLLATE PT_BR
);

CREATE TABLE PERFIL (
    PREFILID   INTEGER NOT NULL,
    NOME       DM_SMALLTEXT COLLATE PT_BR,
    DESCRICAO  DM_LONGTEXT COLLATE PT_BR
);

CREATE TABLE PERFIL_CONF (
    PREFILID   INTEGER NOT NULL,
    NAME       DM_SMALLTEXT NOT NULL COLLATE PT_BR,
    CAPTION    DM_LONGTEXT COLLATE PT_BR,
    PREMISSAO  CHAR(1) CHARACTER SET ISO8859_1
);

CREATE TABLE PRODUTOS (
    PRODUTOID  INTEGER NOT NULL,
    DESCRICAO  DM_LONGTEXT COLLATE PT_BR,
    ESTOQUE    NUMERIC(5,3),
    PRECO      NUMERIC(9,2)
);

CREATE TABLE USUARIOS (
    USUARIOID  INTEGER NOT NULL,
    PREFILID   INTEGER NOT NULL,
    NOME       DM_LONGTEXT COLLATE PT_BR,
    EMAIL      DM_LONGTEXT COLLATE PT_BR,
    LOGIN      VARCHAR(10) CHARACTER SET ISO8859_1 COLLATE PT_BR,
    SENHA      VARCHAR(10) CHARACTER SET ISO8859_1 COLLATE PT_BR,
    VENDEDOR   CHAR(1) CHARACTER SET ISO8859_1 COLLATE PT_BR
);

CREATE TABLE VENDAITEM (
    VENDAID    INTEGER NOT NULL,
    PRODUTOID  INTEGER NOT NULL,
    QTDE       NUMERIC(5,3),
    PRECO      NUMERIC(9,2)
);

CREATE TABLE VENDAS (
    VENDAID    INTEGER NOT NULL,
    CLIENTEID  INTEGER NOT NULL,
    USUARIOID  INTEGER NOT NULL,
    DATA       DATE
);



/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTEID);
ALTER TABLE PERFIL ADD CONSTRAINT PK_PREFIL PRIMARY KEY (PREFILID);
ALTER TABLE PERFIL_CONF ADD CONSTRAINT PK_PERFIL_CONF PRIMARY KEY (PREFILID, NAME);
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (PRODUTOID);
ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (USUARIOID);
ALTER TABLE VENDAITEM ADD CONSTRAINT PK_VENDAITEM PRIMARY KEY (PRODUTOID, VENDAID);
ALTER TABLE VENDAS ADD CONSTRAINT PK_VENDAS PRIMARY KEY (VENDAID);


/******************************************************************************/
/*                                Foreign Keys                                */
/******************************************************************************/

ALTER TABLE PERFIL_CONF ADD CONSTRAINT FK_PERFIL_CONF_1 FOREIGN KEY (PREFILID) REFERENCES PERFIL (PREFILID);
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_1 FOREIGN KEY (PREFILID) REFERENCES PERFIL (PREFILID);
ALTER TABLE VENDAITEM ADD CONSTRAINT FK_VENDAITEM_1 FOREIGN KEY (VENDAID) REFERENCES VENDAS (VENDAID);
ALTER TABLE VENDAITEM ADD CONSTRAINT FK_VENDAITEM_2 FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS (PRODUTOID);
ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_1 FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES (CLIENTEID);
ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_2 FOREIGN KEY (USUARIOID) REFERENCES USUARIOS (USUARIOID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/


SET TERM ^ ;


/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: CLIENTES_BI */
CREATE TRIGGER CLIENTES_BI FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CLIENTEID IS NULL) THEN
    NEW.CLIENTEID = GEN_ID(GEN_CLIENTES_ID,1);
END
^

/* Trigger: PERFIL_BI */
CREATE TRIGGER PERFIL_BI FOR PERFIL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PREFILID IS NULL) THEN
    NEW.PREFILID = GEN_ID(GEN_PERFIL_ID,1);
END
^

/* Trigger: PRODUTOS_BI */
CREATE TRIGGER PRODUTOS_BI FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PRODUTOID IS NULL) THEN
    NEW.PRODUTOID = GEN_ID(GEN_PRODUTOS_ID,1);
END
^

/* Trigger: USUARIOS_BI */
CREATE TRIGGER USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.USUARIOID IS NULL) THEN
    NEW.USUARIOID = GEN_ID(GEN_USUARIOS_ID,1);
END
^

/* Trigger: VENDAS_BI */
CREATE TRIGGER VENDAS_BI FOR VENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.VENDAID IS NULL) THEN
    NEW.VENDAID = GEN_ID(GEN_VENDAS_ID,1);
END
^

SET TERM ; ^

